//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2V10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cenovnik
    {
        public int Id { get; set; }
        public double CenaSat { get; set; }
        public double CenaDan { get; set; }
        public double BrMesta { get; set; }
    }
}
